name: Publish
on:
  release:
    types: [released] # This will only cover actual releases, not pre-releases

jobs:
  release:
    name: Release to PyPI
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v4
      with:
        python-version: "3.x"
        cache: "pip"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip 
        pip install hatch
    
    - run: hatch build
    - run: hatch run test
    
    - name: Publish package distributions to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
